//
//  Constants.swift
//  Bubble Wrap 2.0
//
//  Created by Kyle Nakamura on 5/27/18.
//  Copyright © 2018 Kyle Nakamura. All rights reserved.
//

import UIKit

var demoPicsumImages: [UIImage] = []

struct Constants {
    struct Colors {
        static let appPrimaryColor =  UIColor(red: 26/255, green: 155/255, blue: 229/255, alpha: Alphas.Opaque)  // Bubble Blue
        static let appSecondaryColor =  UIColor.blue.withAlphaComponent(Alphas.Opaque)                           // Transparent Blue
        
        private struct Alphas {
            static let Opaque = CGFloat(1)
            static let SemiOpaque = CGFloat(0.85)
            static let SemiTransparent = CGFloat(0.50)
            static let Transparent = CGFloat(0.30)
        }
        
        struct TextColors {
            static let primaryBlack = UIColor.black.withAlphaComponent(Alphas.SemiOpaque)
            static let secondaryBlack = UIColor.black.withAlphaComponent(Alphas.SemiTransparent)
            static let primaryWhite = UIColor.white
            static let secondaryWhite = UIColor.white.withAlphaComponent(Alphas.SemiOpaque)
        }
        
        struct TabBarColors{
            static let Selected = UIColor.white
            static let NotSelected = appPrimaryColor
        }
    }
}



// Bubble Communities stored as: [email domain : university name]
let existingBubbleCommunities: [String : String] = [
    "acu.edu" : "Abilene Christian University",
    "adelphi.edu" : "Adelphi University",
    "scottlan.edu" : "Agnes Scott College",
    "afit.af.mil" : "Air Force Institute of Technology",
    "aamu.edu" : "Alabama A&M University",
    "alasu.edu" : "Alabama State University",
    "acofi.edu" : "Albertson College of Idaho",
    "albion.edu" : "Albion College",
    "alfred.edu" : "Alfred University",
    "alleg.edu" : "Allegheny College",
    "allencol.edu" : "Allentown College of Saint Francis de Sales",
    "alma.edu" : "Alma College",
    "alverno.edu" : "Alverno College",
    "ambassador.edu" : "Ambassador University",
    "amercoastuniv.edu" : "American Coastline University",
    "t-bird.edu" : "American Graduate School of International Management",
    "aic.edu" : "American International College",
    "american.edu" : "American University",
    "amherst.edu" : "Amherst College",
    "andrews.edu" : "Andrews University",
    "angelo.edu" : "Angelo State University",
    "college.antioch.edu" : "Antioch College",
    "antiochne.edu" : "Antioch New England",
    "antiochla.edu" : "Antioch University-Los Angeles",
    "seattleantioch.edu" : "Antioch University-Seattle",
    "appstate.edu" : "Appalachian State University",
    "aquinas.edu" : "Aquinas College",
    "asu.edu" : "Arizona State University",
    "west.asu.edu" : "Arizona State University West",
    "awc.cc.az.us" : "Arizona Western College",
    "astate.edu" : "Arkansas State University, Jonesboro",
    "atu.edu" : "Arkansas Tech University",
    "armstrong.edu" : "Armstrong State College",
    "ashland.edu" : "Ashland University",
    "assumption.edu" : "Assumption College",
    "auburn.edu" : "Auburn University",
    "aum.edu" : "Auburn University - Montgomery",
    "augsburg.edu" : "Augsburg College",
    "augustana.edu" : "Augustana College, IL",
    "augie.edu" : "Augustana College, SD",
    "aurora.edu" : "Aurora University",
    "austinc.edu" : "Austin College",
    "apsu.edu" : "Austin Peay State University",
    "averett.edu" : "Averett College",
    "avila.edu" : "Avila College",
    "apu.edu" : "Azusa Pacific University",
    "babson.edu" : "Babson College",
    "baldwinw.edu" : "Baldwin-Wallace College",
    "bsu.edu" : "Ball State University",
    "bakeru.edu" : "Baker University",
    "bbc.edu" : "Baptist Bible College",
    "bard.edu" : "Bard College",
    "barry.edu" : "Barry University",
    "bastyr.edu" : "Bastyr University",
    "bates.edu" : "Bates College",
    "bcm.tmc.edu" : "Baylor College of Medicine",
    "baylor.edu" : "Baylor University",
    "beaver.edu" : "Beaver College",
    "belmont.edu" : "Belmont University",
    "beloit.edu" : "Beloit College",
    "bemidji.msus.edu" : "Bemidji State University",
    "benedictine.edu" : "Benedictine College",
    "bennington.edu" : "Bennington College",
    "bentley.edu" : "Bentley College",
    "berea.edu" : "Berea College",
    "berklee.edu" : "Berklee College of Music",
    "bethany.edu" : "Bethany College, CA",
    "bethany.wvnet.edu" : "Bethany College, WV",
    "bethelks.edu" : "Bethel College, KS",
    "bethel.edu" : "Bethel College and Seminary, MN",
    "biola.edu" : "Biola University",
    "bsc.edu" : "Birmingham-Southern College",
    "bhsu.edu" : "Black Hills State University",
    "bloomu.edu" : "Bloomsburg University of Pennsylvania",
    "bluffton.edu" : "Bluffton College",
    "bju.edu" : "Bob Jones University",
    "idbsu.edu" : "Boise State University",
    "bc.edu" : "Boston College",
    "bgsp.edu" : "Boston Graduate School of Psychoanalysis",
    "bu.edu" : "Boston University",
    "bowdoin.edu" : "Bowdoin College",
    "bsu.umd.edu" : "Bowie State University",
    "bgsu.edu" : "Bowling Green State University",
    "bradley.edu" : "Bradley University",
    "brandeis.edu" : "Brandeis University",
    "brenau.edu" : "Brenau University",
    "briar-cliff.edu" : "Briar Cliff College",
    "bridgewater.edu" : "Bridgewater College",
    "byu.edu" : "Brigham Young University",
    "byuh.edu" : "Brigham Young University Hawaii",
    "brown.edu" : "Brown University",
    "bryant.edu" : "Bryant College",
    "brynmawr.edu" : "Bryn Mawr College",
    "bucknell.edu" : "Bucknell University",
    "bvu.edu" : "Buena Vista University",
    "butler.edu" : "Butler University",
    "calcoastuniv.edu" : "California Coast University",
    "caltech.edu" : "California Institute of Technology",
    "callutheran.edu" : "California Lutheran University",
    "csum.edu" : "California Maritime Academy",
    "cnuas.edu" : "California National University",
    "calpoly.edu" : "California Polytechnic State University, San Luis Obispo",
    "csupomona.edu" : "California State Polytechnic University, Pomona",
    "calstate.edu" : "California State University System",
    "csubak.edu" : "California State University, Bakersfield",
    "csuchico.edu" : "California State University, Chico",
    "csudh.edu" : "California State University, Dominguez Hills",
    "csufresno.edu" : "California State University, Fresno",
    "fullerton.edu" : "California State University, Fullerton",
    "csuhayward.edu" : "California State University, Hayward",
    "csulb.edu" : "California State University, Long Beach",
    "calstatela.edu" : "California State University, Los Angeles",
    "monterey.edu" : "California State University, Monterey Bay",
    "csun.edu" : "California State University, Northridge",
    "csus.edu" : "California State University, Sacramento",
    "csusb.edu" : "California State University, San Bernardino",
    "sjsu.edu" : "California State University, San Jose",
    "csusm.edu" : "California State University, San Marcos",
    "csustan.edu" : "California State University, Stanislaus",
    "cup.edu" : "California University of Pennsylvania",
    "calvin.edu" : "Calvin College",
    "campbell.edu" : "Campbell University",
    "campbellsvil.edu" : "Campbellsville College",
    "cameron.edu" : "Cameron University",
    "canisius.edu" : "Canisius College",
    "carleton.edu" : "Carleton College",
    "carlow.edu" : "Carlow College",
    "cmu.edu" : "Carnegie Mellon University",
    "carroll.edu" : "Carroll College, MT",
    "cc.edu" : "Carroll College, WI",
    "cn.edu" : "Carson-Newman College",
    "carthage.edu" : "Carthage College",
    "cwru.edu" : "Case Western Reserve University",
    "csc.vsc.edu" : "Castleton State University",
    "cua.edu" : "The Catholic University of America",
    "cedarville.edu" : "Cedarville College",
    "centenary.edu" : "Centenary College of Louisiana",
    "central.edu" : "Central College",
    "ccsu.ctstateu.edu" : "Central Connecticut State University",
    "cmc.edu" : "Central Methodist College",
    "cmich.edu" : "Central Michigan University",
    "cmsu.edu" : "Central Missouri State University",
    "cwu.edu" : "Central Washington University",
    "centre.edu" : "Centre College",
    "csc.edu" : "Chadron State College",
    "champlain.edu" : "Champlain College",
    "chapman.edu" : "Chapman University",
    "chatham.edu" : "Chatham College",
    "chesapeake.edu" : "Chesapeake College",
    "cheyney.edu" : "Cheyney University",
    "csopp.edu" : "The Chicago School of Professional Psychology",
    "cbu.edu" : "Christian Brothers University",
    "cts.edu" : "Christian Theological Seminary",
    "cnu.edu" : "Christopher Newport University",
    "citadel.edu" : "The Citadel",
    "cityu.edu" : "City University",
    "cuny.edu" : "City University of New York",
    "cgs.edu" : "Claremont Graduate School",
    "mckenna.edu" : "Claremont McKenna College",
    "clarion.edu" : "Clarion University of Pennsylvania",
    "clarku.edu" : "Clark University",
    "clarke.edu" : "Clarke College",
    "clarkson.edu" : "Clarkson University",
    "csc.peachnet.edu" : "Clayton State College",
    "clemson.edu" : "Clemson University",
    "csuohio.edu" : "Cleveland State University",
    "clinch.edu" : "Clinch Valley College",
    "coastal.edu" : "Coastal Carolina University",
    "coe.edu" : "Coe College",
    "coker.edu" : "Coker College",
    "colby.edu" : "Colby College",
    "colgate.edu" : "Colgate University",
    "coa.edu" : "College of the Atlantic",
    "cofc.edu" : "College of Charleston",
    "ceu.edu" : "College of Eastern Utah",
    "holycross.edu" : "College of the Holy Cross",
    "stkate.edu" : "College of Saint Catherine",
    "stfrancis.edu" : "College of St. Francis",
    "strose.edu" : "College of Saint Rose",
    "css.edu" : "College of St. Scholastica",
    "wm.edu" : "College of William and Mary",
    "wooster.edu" : "The College of Wooster",
    "ccu.edu" : "Colorado Christian University",
    "cc.colorado.edu" : "Colorado College",
    "mines.colorado.edu" : "Colorado School of Mines",
    "colostate.edu" : "Colorado State University",
    "colum.edu" : "Columbia College Chicago",
    "colsouth.edu" : "Columbia Southern University",
    "cuc.edu" : "Columbia Union College",
    "columbia.edu" : "Columbia University",
    "ccaa.edu" : "Concordia College-Ann Arbor",
    "cord.edu" : "Concordia College-Moorhead",
    "csp.edu" : "Concordia College-St. Paul",
    "ccsn.edu" : "Concordia College-Seward",
    "cuis.edu" : "Concordia University River Forest, Illinois",
    "conncoll.edu" : "Connecticut College",
    "cooper.edu" : "The Cooper Union for the Advancement of Science and Art",
    "coppin.umd.edu" : "Coppin State College",
    "cornell-iowa.edu" : "Cornell College",
    "cornell.edu" : "Cornell University",
    "creighton.edu" : "Creighton University",
    "curry.edu" : "Curry College",
    "daemen.edu" : "Daemen College",
    "dsu.edu" : "Dakota State University",
    "dwu.edu" : "Dakota Wesleyan University",
    "dbu.edu" : "Dallas Baptist University",
    "dana.edu" : "Dana College",
    "dwc.edu" : "Daniel Webster College",
    "dartmouth.edu" : "Dartmouth College",
    "davenport.edu" : "Davenport College Detroit College of Business",
    "davidson.edu" : "Davidson College",
    "dne.wvnet.edu" : "Davis & Elkins College",
    "dsc.edu" : "Delaware State University",
    "deltast.edu" : "Delta State University",
    "denison.edu" : "Denison University",
    "depaul.edu" : "DePaul University",
    "depauw.edu" : "DePauw University",
    "devrycols.edu" : "DeVry Institute of Technology",
    "devry.edu" : "DeVry Institute of Technology-Dallas",
    "devry-phx.edu" : "DeVry Institute of Technology-Phoenix",
    "dickinson.edu" : "Dickinson College",
    "dsu.nodak.edu" : "Dickinson State University",
    "dillard.edu" : "Dillard University",
    "dominican.edu" : "Dominican College",
    "Dordt.edu" : "Dordt College",
    "dowling.edu" : "Dowling College",
    "drake.edu" : "Drake University",
    "drew.edu" : "Drew University",
    "drexel.edu" : "Drexel University",
    "drury.edu" : "Drury College",
    "duke.edu" : "Duke University",
    "duq.edu" : "Duquesne University",
    "earlham.edu" : "Earlham College",
    "ecu.edu" : "East Carolina University",
    "ecok.edu" : "East Central University",
    "esu.edu" : "East Stroudsburg State University of Pennsylvania",
    "etsu-tn.edu" : "East Tennessee State University",
    "etsu.edu" : "East Texas State University",
    "ecsu.ctstateu.edu" : "Eastern Connecticut State University",
    "eiu.edu" : "Eastern Illinois University",
    "eku.edu" : "Eastern Kentucky University",
    "emu.edu" : "Eastern Mennonite University",
    "emich.edu" : "Eastern Michigan University",
    "enmu.edu" : "Eastern New Mexico University",
    "eosc.osshe.edu" : "Eastern Oregon State College",
    "ewu.edu" : "Eastern Washington University",
    "edgewood.edu" : "Edgewood College",
    "edinboro.edu" : "Edinboro University of Pennsylvania",
    "ecsu.edu" : "Elizabeth City State University",
    "etown.edu" : "Elizabethtown College",
    "elmhurst.edu" : "Elmhurst College",
    "elon.edu" : "Elon College",
    "erau.edu" : "Embry-Riddle Aeronautical University",
    "emerson.edu" : "Emerson College",
    "emmanuel.edu" : "Emmanuel College",
    "emporia.edu" : "Emporia State University",
    "emory.edu" : "Emory University",
    "evergreen.edu" : "Evergreen State College",
    "fdu.edu" : "Fairleigh Dickinson University",
    "fairmont.wvnet.edu" : "Fairmont State College",
    "fsufay.edu" : "Fayetteville State University",
    "ferris.edu" : "Ferris State University",
    "fielding.edu" : "Fielding Institute",
    "fisk.edu" : "Fisk University",
    "fsc.edu" : "Fitchburg State College",
    "famu.edu" : "Florida Agricultural and Mechanical University",
    "fau.edu" : "Florida Atlantic University",
    "fgcu.edu" : "Florida Gulf Coast University",
    "fit.edu" : "Florida Institute of Technology",
    "fiu.edu" : "Florida International University",
    "fsu.edu" : "Florida State University",
    "fontbonne.edu" : "Fontbonne College",
    "fordham.edu" : "Fordham University",
    "fhsu.edu" : "Fort Hays State University",
    "fortlewis.edu" : "Fort Lewis College",
    "fandm.edu" : "Franklin and Marshall College",
    "fplc.edu" : "Franklin Pierce Law Center",
    "franklin.edu" : "Franklin University",
    "fresno.edu" : "Fresno Pacific University",
    "friends.edu" : "Friends University",
    "fsu.umd.edu" : "Frostburg State University",
    "fuller.edu" : "Fuller Theological Seminary",
    "furman.edu" : "Furman University",
    "gallaudet.edu" : "Gallaudet University",
    "gannon.edu" : "Gannon University",
    "geneva.edu" : "Geneva College",
    "gfc.edu" : "George Fox College",
    "gmu.edu" : "George Mason University",
    "gwu.edu" : "George Washington University",
    "georgetown.edu" : "Georgetown University",
    "gac.peachnet.edu" : "Georgia College",
    "gatech.edu" : "Georgia Institute of Technology",
    "gasou.edu" : "Georgia Southern University",
    "gsw.peachnet.edu" : "Georgia Southwestern College",
    "gsu.edu" : "Georgia State University",
    "georgian.edu" : "Georgian Court College",
    "gettysburg.edu" : "Gettysburg College",
    "gmi.edu" : "GMI Engineering and Management Institute",
    "ggu.edu" : "Golden Gate University",
    "gbc.edu" : "Goldey-Beacom College",
    "gonzaga.edu" : "Gonzaga University",
    "goshen.edu" : "Goshen College",
    "goucher.edu" : "Goucher College",
    "bgu.edu" : "Governors State University",
    "grace.edu" : "Grace College",
    "graceland.edu" : "Graceland College",
    "gvsu.edu" : "Grand Valley State University",
    "greenleaf.edu" : "Greenleaf University",
    "grin.edu" : "Grinnell College",
    "guilford.edu" : "Guilford College",
    "gac.edu" : "Gustavus Adolphus College",
    "hamilton.edu" : "Hamilton College",
    "hamline.edu" : "Hamline University",
    "hsc.edu" : "Hampden-Sydney College",
    "hampshire.edu" : "Hampshire College",
    "hamptonu.edu" : "Hampton University",
    "hanover.edu" : "Hanover College",
    "harding.edu" : "Harding University",
    "hartwick.edu" : "Hartwick College",
    "harvard.edu" : "Harvard University",
    "hmc.edu" : "Harvey Mudd College",
    "haskell.edu" : "Haskell Indian Nations University",
    "hastings.edu" : "Hastings College",
    "haverford.edu" : "Haverford College in Pennsylvania",
    "hpu.edu" : "Hawaii Pacific University",
    "heidelberg.edu" : "Heidelberg College",
    "hendrix.edu" : "Hendrix College",
    "hesston.edu" : "Hesston College",
    "highpoint.edu" : "High Point University",
    "hillsdale.edu" : "Hillsdale College",
    "hiram.edu" : "Hiram College",
    "hws.edu" : "Hobart and William Smith Colleges",
    "hofstra.edu" : "Hofstra University",
    "hollins.edu" : "Hollins College",
    "hood.edu" : "Hood College",
    "hope.edu" : "Hope College",
    "howard.edu" : "Howard University",
    "humboldt.edu" : "Humboldt State University",
    "hunter.cuny.edu" : "Hunter College",
    "huntingdon.edu" : "Huntingdon College",
    "huntcol.edu" : "Huntington College",
    "ici.edu" : "ICI University",
    "isu.edu" : "Idaho State University",
    "ibc.edu" : "Illinois Benedictine College",
    "iit.edu" : "Illinois Institute of Technology",
    "ilstu.edu" : "Illinois State University",
    "iwctx.edu" : "Incarnate Word College",
    "indtech.edu" : "Indiana Institute of Technology",
    "indstate.edu" : "Indiana State University",
    "columbus.iupui.edu" : "Indiana University/Purdue University at Columbus",
    "ipfw.indiana.edu" : "Indiana University/Purdue University at Fort Wayne",
    "iupui.edu" : "Indiana University/Purdue University at Indianapolis",
    "indiana.edu" : "Indiana University at Bloomington",
    "iusb.indiana.edu" : "Indiana University at South Bend",
    "iup.edu" : "Indiana University of Pennsylvania",
    "ius.indiana.edu" : "Indiana University Southeast at New Albany",
    "indwes.edu" : "Indiana Wesleyan University, Marion",
    "metro.inter.edu" : "Inter American University of Puerto Rico Metropolitan Campus",
    "iona.edu" : "Iona College",
    "iastate.edu" : "Iowa State University",
    "ithaca.edu" : "Ithaca College",
    "jsums.edu" : "Jackson State University",
    "ju.edu" : "Jacksonville University",
    "jsu.edu" : "Jacksonville State University",
    "jmu.edu" : "James Madison University",
    "jc.edu" : "Jamestown College",
    "jtsa.edu" : "The Jewish Theological Seminary",
    "jbu.edu" : "John Brown University",
    "jfku.edu" : "John F. Kennedy University",
    "jhu.edu" : "Johns Hopkins University",
    "jbc.edu" : "Johnson Bible College",
    "jcsu.edu" : "Johnson C. Smith University",
    "jwu.edu" : "Johnson & Wales University",
    "jones.edu" : "Jones College",
    "judson.edu" : "Judson College",
    "juniata.edu" : "Juniata College",
    "kzoo.edu" : "Kalamazoo College",
    "ksu.edu" : "Kansas State University",
    "kwu.edu" : "Kansas Wesleyan University",
    "kean.edu" : "Kean College",
    "keene.edu" : "Keene State College",
    "kent.edu" : "Kent State University",
    "kenyon.edu" : "Kenyon College",
    "kings.edu" : "King's College",
    "knox.edu" : "Knox College",
    "kutztown.edu" : "Kutztown University of Pennsylvania",
    "lasierra.edu" : "La Sierra University",
    "lgc.peachnet.edu" : "LaGrange College",
    "lafayette.edu" : "Lafayette College",
    "lfc.edu" : "Lake Forest College",
    "lssu.edu" : "Lake Superior State University",
    "lamar.edu" : "Lamar University",
    "lunet.edu" : "Langston University",
    "lasalle.edu" : "LaSalle University",
    "lawrence.edu" : "Lawrence University",
    "ltu.edu" : "Lawrence Technological University",
    "lvc.edu" : "Lebanon Valley College",
    "lehigh.edu" : "Lehigh Univervsity",
    "lemoyne.edu" : "Le Moyne College",
    "lrc.edu" : "Lenoir-Rhyne College",
    "letu.edu" : "LeTourneau University",
    "lclark.edu" : "Lewis & Clark College",
    "lcsc.edu" : "Lewis-Clark State College",
    "lewisu.edu" : "Lewis University",
    "liberty.edu" : "Liberty University",
    "lincoln.edu" : "Lincoln University",
    "linfield.edu" : "Linfield College",
    "lhup.edu" : "Lock Haven University of Pennsylvania",
    "llu.edu" : "Loma Linda University",
    "liunet.edu" : "Long Island University",
    "lwc.edu" : "Longwood College",
    "loras.edu" : "Loras College",
    "lacollege.edu" : "Louisiana College",
    "lsua.edu" : "Louisiana State University at Alexandria",
    "lsu.edu" : "Louisiana State University at Shreveport",
    "latech.edu" : "Louisiana Tech University",
    "loyola.edu" : "Loyola College",
    "lmu.edu" : "Loyola Marymount University",
    "luc.edu" : "Loyola University Chicago",
    "luther.edu" : "Luther College",
    "luthersem.edu" : "Luther Seminary",
    "lycoming.edu" : "Lycoming College",
    "lynchburg.edu" : "Lynchburg College",
    "lsc.vsc.edu" : "Lyndon State College",
    "lyon.edu" : "Lyon College",
    "macalstr.edu" : "Macalester College",
    "mum.edu" : "Maharishi University of Management",
    "malone.edu" : "Malone College",
    "mancol.edu" : "Manhattan College",
    "mankato.msus.edu" : "Mankato State University",
    "mnsfld.edu" : "Mansfield University of Pennsylvania",
    "marietta.edu" : "Marietta College",
    "marist.edu" : "Marist College",
    "marlboro.edu" : "Marlboro College",
    "mu.edu" : "Marquette University",
    "marshall.edu" : "Marshall University",
    "mbc.edu" : "Mary Baldwin College",
    "marymt.edu" : "Marymount College",
    "marymount.edu" : "Marymount University",
    "mwc.edu" : "Mary Washington College",
    "mit.edu" : "Massachusetts Institute of Technology",
    "mcm.acu.edu" : "McMurry University",
    "mcneese.edu" : "McNeese State University",
    "mcg.edu" : "Medical College of Georgia",
    "mcw.edu" : "Medical College of Wisconsin",
    "mercer.peachnet.edu" : "Mercer University",
    "mercy.edu" : "Mercyhurst College",
    "meredith.edu" : "Meredith College",
    "messiah.edu" : "Messiah College",
    "mscd.edu" : "Metropolitan State College of Denver",
    "metro.msus.edu" : "Metropolitan State University",
    "muohio.edu" : "Miami Christian University, mcu.edu",
    "msu.edu" : "Michigan State University",
    "mtu.edu" : "Michigan Technological University",
    "manc.edu" : "Mid-America Nazarene College",
    "middlebury.edu" : "Middlebury College",
    "mgc.peachnet.edu" : "Middle Georgia College",
    "mtsu.edu" : "Middle Tennessee State University",
    "mwsu.edu" : "Midwestern State University",
    "millersv.edu" : "Millersville University of Pennsylvania",
    "milligan-college.tn.us" : "Milligan College",
    "millikin.edu" : "Millikin University",
    "millsaps.edu" : "Millsaps College",
    "msoe.edu" : "Milwaukee School of Engineering",
    "misu.nodak.edu" : "Minot State University",
    "mcad.edu" : "Minneapolis College of Art and Design",
    "mc.edu" : "Mississippi College",
    "msstate.edu" : "Mississippi State University",
    "muw.edu" : "Mississippi University for Women",
    "mssc.edu" : "Missouri Southern State College",
    "mwsc.edu" : "Missouri Western State College",
    "molloy.edu" : "Molloy College",
    "monm.edu" : "Monmouth College",
    "monmouth.edu" : "Monmouth University",
    "msubillings.edu" : "Montana State University-Billings",
    "montana.edu" : "Montana State University-Bozeman",
    "nmclites.edu" : "Montana State University-Northern",
    "mtech.edu" : "Montana Tech",
    "montclair.edu" : "Montclair State University",
    "montreat.edu" : "Montreat College",
    "moravian.edu" : "Moravian College",
    "moorhead.msus.edu" : "Moorhead State University",
    "morgan.edu" : "Morgan State University",
    "mscfs.edu" : "Mount Senario College",
    "mtholyoke.edu" : "Mount Holyoke College",
    "msjnet.edu" : "Mount Saint Joseph College",
    "msmc.edu" : "Mount Saint Mary College",
    "muc.edu" : "Mount Union College",
    "mursuky.edu" : "Murray State University",
    "muskingum.edu" : "Muskingum College",
    "ndu.edu" : "National Defense University",
    "nl.edu" : "National-Louis University",
    "ntu.edu" : "National Technological University",
    "nu.edu" : "National University",
    "nps.navy.mil" : "Naval Postgraduate School",
    "naz.edu" : "Nazareth College",
    "newberry.edu" : "Newberry College",
    "neit.edu" : "New England Institute of Technology",
    "newcollege.edu" : "New College of California",
    "nhc.edu" : "New Hampshire College",
    "njit.edu" : "New Jersey Institute of Technology",
    "nmhu.edu" : "New Mexico Highlands University",
    "nmt.edu" : "New Mexico Institute of Mining & Technology",
    "nmsu.edu" : "New Mexico State University",
    "nyit.edu" : "New York Institute of Technology",
    "nyu.edu" : "New York University",
    "niagara.edu" : "Niagara University",
    "nich.edu" : "Nicholls State University",
    "nsu.edu" : "Norfolk State University",
    "nasc.mass.edu" : "North Adams State College",
    "NCCU.edu" : "North Carolina Central University",
    "ncat.edu" : "North Carolina A&T State University",
    "ncsu.edu" : "North Carolina State University",
    "ncwc.edu" : "North Carolina Wesleyan College",
    "ncbc.edu" : "North Central Bible College",
    "ndsu.nodak.edu" : "North Dakota State University",
    "northland.edu" : "Northland College",
    "npcts.edu" : "North Park College and Theological Seminary",
    "neiu.edu" : "Northeastern Illinois University",
    "nlu.edu" : "Northeastern Louisiana University",
    "nsuok.edu" : "Northeastern State University",
    "northeastern.edu" : "Northeastern University",
    "nau.edu" : "Northern Arizona University",
    "niu.edu" : "Northern Illinois University",
    "nku.edu" : "Northern Kentucky University",
    "nmu.edu" : "Northern Michigan University",
    "northern.edu" : "Northern State University",
    "nwmissouri.edu" : "Northwest Missouri State University",
    "nnc.edu" : "Northwest Nazarene College",
    "nwciowa.edu" : "Northwestern College of Iowa",
    "nsula.edu" : "Northwestern State University",
    "nwu.edu" : "Northwestern University",
    "norwich.edu" : "Norwich University",
    "nova.edu" : "Nova Southeastern University",
    "oakland.edu" : "Oakland University",
    "oberlin.edu" : "Oberlin College",
    "oxy.edu" : "Occidental College",
    "odc.edu" : "Ohio Dominican College",
    "onu.edu" : "Ohio Northern University",
    "ohio-state.edu" : "Ohio State University, Columbus",
    "marion.ohio-state.edu" : "Ohio State University, Marion",
    "owu.edu" : "Ohio Wesleyan University",
    "ohiou.edu" : "Ohio University, Athens",
    "okbu.edu" : "Oklahoma Baptist University",
    "okcu.edu" : "Oklahoma City University",
    "okstate.edu" : "Oklahoma State University",
    "odu.edu" : "Old Dominion University",
    "olivet.edu" : "Olivet Nazarene University",
    "oru.edu" : "Oral Roberts University",
    "ogi.edu" : "Oregon Graduate Institute of Science and Technology",
    "ohsu.edu" : "Oregon Health Sciences University",
    "oit.osshe.edu" : "Oregon Institute of Technology",
    "orst.edu" : "Oregon State University",
    "otterbein.edu" : "Otterbein College",
    "ollusa.edu" : "Our Lady of the Lake University",
    "pace.edu" : "Pace University",
    "plu.edu" : "Pacific Lutheran University",
    "puc.edu" : "Pacific Union College",
    "pacificu.edu" : "Pacific University",
    "pwu.com" : "Pacific Western University",
    "pbac.edu" : "Palm Beach Atlantic College",
    "Peace.edu" : "Peace College",
    "pembroke.edu" : "Pembroke State University",
    "sshechan.edu" : "Pennsylvania State System of Higher Education",
    "psu.edu" : "Pennsylvania State University",
    "sl.psu.edu" : "Pennsylvania State University-Schuylkill Campus",
    "pcci.edu" : "Pensacola Christian College",
    "pepperdine.edu" : "Pepperdine University",
    "peru.edu" : "Peru State College",
    "philacol.edu" : "Philadelphia College of Textiles and Science",
    "phillips.edu" : "Phillips University",
    "pittstate.edu" : "Pittsburg State University",
    "pitzer.edu" : "Pitzer College",
    "platt.edu" : "Platt College",
    "plymouth.edu" : "Plymouth State College",
    "plnu.edu" : "Point Loma Nazarene University",
    "poly.edu" : "Polytechnic University of New York",
    "pupr.edu" : "Polytechnic University of Puerto Rico",
    "pomona.edu" : "Pomona College",
    "pdx.edu" : "Portland State University",
    "pvamu.edu" : "Prairie View A&M University",
    "pratt.edu" : "Pratt Institute",
    "prescott.edu" : "Prescott College",
    "princeton.edu" : "Princeton University",
    "presby.edu" : "Presbyterian College",
    "providence.edu" : "Providence College",
    "purdue.edu" : "Purdue University Calumet",
    "purduenc.edu" : "Purdue University North Central",
    "quincy.edu" : "Quincy University",
    "quinnipiac.edu" : "Quinnipiac College",
    "runet.edu" : "Radford University",
    "ramapo.edu" : "Ramapo College",
    "rmc.edu" : "Randolph-Macon College",
    "rmwc.edu" : "Randolph-Macon Woman's College",
    "reed.edu" : "Reed College",
    "regent.edu" : "Regent University",
    "regis.edu" : "Regis University",
    "rpi.edu" : "Rensselaer Polytechnic Institute",
    "ric.edu" : "Rhode Island College",
    "rhodes.edu" : "Rhodes College",
    "rice.edu" : "Rice University",
    "stockton.edu" : "Richard Stockton College of New Jersey",
    "rider.edu" : "Rider University",
    "Ripon.EDU" : "Ripon College",
    "riv.edu" : "Rivier College",
    "roanoke.edu" : "Roanoke College",
    "rit.edu" : "Rochester Institute of Technology",
    "rockefeller.edu" : "The Rockefeller University",
    "rockford.edu" : "Rockford College",
    "rockhurst.edu" : "Rockhurst College",
    "rocky.edu" : "Rocky Mountain College",
    "rwu.edu" : "Roger Williams University",
    "rollins.edu" : "Rollins College",
    "rosary.edu" : "Rosary College",
    "rose-hulman.edu" : "Rose-Hulman Institute of Technology",
    "rowan.edu" : "Rowan College",
    "rutgers.edu" : "Rutgers University",
    "sage.edu" : "The Sage Colleges",
    "sacredheart.edu" : "Sacred Heart University, CT",
    "usc.clu.edu" : "Sacred Heart University, PR",
    "svsu.edu" : "Saginaw Valley State University",
    "sau.edu" : "St. Ambrose University",
    "sapc.edu" : "St. Andrews Presbyterian College",
    "anselm.edu" : "Saint Anselm College",
    "sbu.edu" : "St. Bonaventure University",
    "stcloud.msus.edu" : "Saint Cloud State University",
    "stedwards.edu" : "Saint Edward's University",
    "sfcpa.edu" : "Saint Francis College",
    "sjca.edu" : "St. John's College-Annapolis",
    "sjcsf.edu" : "St. John's College-Santa Fe",
    "csbsju.edu" : "Saint John's University, MN",
    "stjohns.edu" : "Saint John's University, NY",
    "sjc.edu" : "St. Joseph College, CT",
    "saintjoe.edu" : "Saint Joseph's College, IN",
    "sjcme.edu" : "St. Joseph's College, ME",
    "sju.edu" : "Saint Joseph's University",
    "stlawu.edu" : "St. Lawrence University",
    "stlcop.edu" : "St. Louis College of Pharmacy",
    "slu.edu" : "Saint Louis University",
    "stmartin.edu" : "St. Martin's College",
    "smcks.edu" : "Saint Mary College",
    "saintmarys.edu" : "Saint Mary's College, IN",
    "stmarys-ca.edu" : "Saint Mary's College of California",
    "smumn.edu" : "Saint Mary's University of Minnesota",
    "smcvt.edu" : "Saint Michael's College",
    "stolaf.edu" : "Saint Olaf College",
    "stu.edu" : "St. Thomas University, FL",
    "stvincent.edu" : "Saint Vincent College",
    "sxu.edu" : "Saint Xavier University",
    "ssu.umd.edu" : "Salisbury State University",
    "skc.edu" : "Salish Kootenai College",
    "shsu.edu" : "Sam Houston State University",
    "samford.edu" : "Samford University",
    "sdsu.edu" : "San Diego State University",
    "sfsu.edu" : "San Francisco State University",
    "scu.edu" : "Santa Clara University",
    "slc.edu" : "Sarah Lawrence College",
    "artic.edu" : "School of the Art Institute of Chicago",
    "spu.edu" : "Seattle Pacific University",
    "seattleu.edu" : "Seattle University",
    "shu.edu" : "Seton Hall University",
    "sewanee.edu" : "Sewanee, University of the South",
    "shawnee.edu" : "Shawnee State University",
    "su.edu" : "Shenandoah University",
    "ship.edu" : "Shippensburg University of Pennsylvania",
    "shorter.edu" : "Shorter College",
    "simmons.edu" : "Simmons College",
    "simons-rock.edu" : "Simon's Rock College",
    "simpson.edu" : "Simpson College",
    "skidmore.edu" : "Skidmore College",
    "sru.edu" : "Slippery Rock University of Pennsylvania",
    "smith.edu" : "Smith College",
    "sonoma.edu" : "Sonoma State University",
    "sdsmt.edu" : "South Dakota School of Mines and Technology",
    "sdstate.edu" : "South Dakota State University",
    "semo.edu" : "Southeast Missouri State University",
    "selu.edu" : "Southeastern Louisiana University",
    "southern.edu" : "Southern College",
    "sct.edu" : "Southern College of Technology",
    "scwww.ctstateu.edu" : "Southern Connecticut State University",
    "siu.edu" : "Southern Illinois University-Carbondale",
    "siue.edu" : "Southern Illinois University-Edwardsville",
    "smu.edu" : "Southern Methodist University",
    "snu.edu" : "Southern Nazarene University",
    "sosc.osshe.edu" : "Southern Oregon State College",
    "subr.edu" : "Southern University",
    "suu.edu" : "Southern Utah University",
    "stcl.edu" : "South Texas College of Law",
    "sbuniv.edu" : "Southwest Baptist University",
    "smsu.edu" : "Southwest Missouri State University",
    "southwest.msus.edu" : "Southwest State University",
    "swt.edu" : "Southwest Texas State University",
    "swac.edu" : "Southwestern Adventist College",
    "southwestern.edu" : "Southwestern University",
    "auc.edu" : "Spelman College",
    "arbor.edu" : "Spring Arbor College",
    "shc.edu" : "Spring Hill College",
    "stanford.edu" : "Stanford University",
    "sunycentral.edu" : "State University of New York System",
    "albany.edu" : "State University of New York at Albany",
    "alfredtech.edu" : "State University of New York College of Technology at Alfred",
    "binghamton.edu" : "State University of New York at Binghamton",
    "brockport.edu" : "State University of New York College at Brockport",
    "buffalo.edu" : "State University of New York at Buffalo",
    "snybuf.edu" : "State University of New York College at Buffalo, Buffalo State College",
    "cobleskill.edu" : "State University of New York College of Agriculture and Technology at Cobleskill",
    "cortland.edu" : "State University of New York College at Cortland",
    "esf.edu" : "State University of New York College of Environmental Science and Forestry",
    "farmingdale.edu" : "State University of New York at Farmingdale",
    "fredonia.edu" : "State University of New York at Fredonia",
    "geneseo.edu" : "State University of New York College at Geneseo",
    "newpaltz.edu" : "State University of New York College at New Paltz",
    "oswego.edu" : "State University of New York at Oswego",
    "plattsburgh.edu" : "State University of New York at Plattsburgh",
    "potsdam.edu" : "State University of New York College at Potsdam",
    "sunysb.edu" : "State University of New York at Stony Brook",
    "sunyit.edu" : "State University of New York Institute of Technology at Utica/Rome",
    "sfasu.edu" : "Stephen F. Austin State University",
    "stephens.edu" : "Stephens College",
    "stetson.edu" : "Stetson University",
    "stevens-tech.edu" : "Stevens Institute of Technology",
    "strayer.edu" : "Strayer College",
    "suffolk.edu" : "Suffolk University",
    "sulross.edu" : "Sul Ross State University",
    "summitunivofla.edu" : "Summit University of Louisiana",
    "susqu.edu" : "Susquehanna University",
    "swarthmore.edu" : "Swarthmore College",
    "sbc.edu" : "Sweet Briar College",
    "syr.edu" : "Syracuse University",
    "tabor.edu" : "Tabor College",
    "tarleton.edu" : "Tarleton State University",
    "tayloru.edu" : "Taylor University",
    "tc.columbia.edu" : "Teachers College, Columbia University",
    "mcrest.edu" : "Teikyo Marycrest University",
    "temple.edu" : "Temple University",
    "tnstate.edu" : "Tennessee State University",
    "tntech.edu" : "Tennessee Technological University",
    "tamiu.edu" : "Texas A&M International University",
    "tamu.edu" : "Texas A&M University-College Station",
    "tamucc.edu" : "Texas A&M University-Corpus Christi",
    "taiu.edu" : "Texas A&M University-Kingsville",
    "tcu.edu" : "Texas Christian University",
    "tsu.edu" : "Texas Southern University",
    "ttu.edu" : "Texas Tech University",
    "ttuhsc.edu" : "Texas Tech University-Health Sciences Center",
    "twu.edu" : "Texas Woman's University",
    "thomas.edu" : "Thomas College",
    "tesc.edu" : "Thomas Edison State College",
    "tju.edu" : "Thomas Jefferson University",
    "thomasmore.edu" : "Thomas More College",
    "towson.edu" : "Towson State University",
    "transy.edu" : "Transylvania University",
    "trenton.edu" : "Trenton State College",
    "trincoll.edu" : "Trinity College, CT",
    "DC" : "Trinity College",
    "trinity.edu" : "Trinity University",
    "tsufl.edu" : "Troy State University",
    "truman.edu" : "Truman State University",
    "tucsonu.edu" : "Tucson University",
    "tufts.edu" : "Tufts University",
    "tulane.edu" : "Tulane University",
    "tusk.edu" : "Tuskegee University",
    "union.edu" : "Union College",
    "tui.edu" : "The Union Institute",
    "uu.edu" : "Union University",
    "usafa.af.mil" : "United States Air Force Academy",
    "usiu.edu" : "United States International University",
    "usmma.edu" : "United States Merchant Marine Academy",
    "usma.edu" : "United States Military Academy",
    "nadn.navy.mil" : "United States Naval Academy",
    "usuhs.mil" : "The Uniformed Services University of the Health Sciences",
    "ursinus.edu" : "Ursinus College",
    "uakron.edu" : "University of Akron",
    "uab.edu" : "University of Alabama at Birmingham",
    "uah.edu" : "University of Alabama at Huntsville",
    "ua.edu" : "University of Alabama at Tuscaloosa",
    "alaska.edu" : "University of Alaska",
    "uaa.alaska.edu" : "University of Alaska-Anchorage",
    "arizona.edu" : "University of Arizona",
    "uark.edu" : "University of Arkansas - Fayetteville",
    "ualr.edu" : "University of Arkansas - Little Rock",
    "uams.edu" : "University of Arkansas for Medical Sciences",
    "uamont.edu" : "University of Arkansas - Monticello",
    "ubalt.edu" : "University of Baltimore",
    "bridgeport.edu" : "University of Bridgeport",
    "berkeley.edu" : "University of California, Berkeley",
    "ucdavis.edu" : "University of California, Davis",
    "uci.edu" : "University of California, Irvine",
    "ucla.edu" : "University of California, Los Angeles",
    "ucr.edu" : "University of California, Riverside",
    "ucsd.edu" : "University of California, San Diego",
    "ucsf.edu" : "University of California, San Francisco",
    "ucsb.edu" : "University of California, Santa Barbara",
    "ucsc.edu" : "University of California, Santa Cruz",
    "uca.edu" : "University of Central Arkansas",
    "ucf.edu" : "University of Central Florida",
    "uchaswv.edu" : "University of Charleston",
    "uchicago.edu" : "University of Chicago",
    "uc.edu" : "University of Cincinnati",
    "colorado.edu" : "University of Colorado at Boulder",
    "uccs.edu" : "University of Colorado at Colorado Springs",
    "cudenver.edu" : "University of Colorado at Denver",
    "hsc.colorado.edu" : "University of Colorado Health Sciences Center",
    "uconn.edu" : "University of Connecticut",
    "udallas.edu" : "University of Dallas",
    "udayton.edu" : "University of Dayton",
    "udel.edu" : "University of Delaware",
    "du.edu" : "University of Denver",
    "udc.edu" : "University of the District of Columbia",
    "udmercy.edu" : "University of Detroit Mercy",
    "dbq.edu" : "University of Dubuque",
    "evansville.edu" : "University of Evansville",
    "ufl.edu" : "University of Florida",
    "uga.edu" : "University of Georgia",
    "ugf.edu" : "University of Great Falls",
    "uog.edu" : "University of Guam",
    "hartford.edu" : "University of Hartford",
    "uhh.hawaii.edu" : "University of Hawaii at Hilo Physics and Astronomy",
    "hawaii.edu" : "University of Hawaii at Manoa",
    "uh.edu" : "University of Houston",
    "uidaho.edu" : "University of Idaho",
    "uic.edu" : "University of Illinois at Chicago",
    "sangamon.edu" : "University of Illinois at Springfield",
    "uiuc.edu" : "University of Ilinois at Urbana-Champaign",
    "uindy.edu" : "University of Indianapolis",
    "uiowa.edu" : "University of Iowa",
    "ukans.edu" : "University of Kansas",
    "kumc.edu" : "University of Kansas School of Medicine",
    "uky.edu" : "University of Kentucky",
    "ulaverne.edu" : "University of La Verne",
    "louisville.edu" : "University of Louisville",
    "maine.edu" : "University of Maine System",
    "ume.maine.edu" : "University of Maine",
    "umf.maine.edu" : "University of Maine at Farmington",
    "umfk.maine.edu" : "University of Maine at Fort Kent",
    "umm.maine.edu" : "University of Maine at Machias",
    "umpi.maine.edu" : "University of Maine at Presque Island",
    "ab.umd.edu" : "University of Maryland at Baltimore",
    "umbc.edu" : "University of Maryland at Baltimore County",
    "umcp.umd.edu" : "University of Maryland at College Park",
    "umuc.edu" : "University of Maryland - University College",
    "umassp.edu" : "University of Massachusetts System",
    "umass.edu" : "University of Massachusetts at Amherst",
    "umassd.edu" : "University of Massachusetts at Dartmouth",
    "uml.edu" : "University of Massachusetts at Lowell",
    "memphis.edu" : "University of Memphis",
    "miami.edu" : "University of Miami",
    "umich.edu" : "University of Michigan-Ann Arbor",
    "umd.umich.edu" : "University of Michigan-Dearborn",
    "crk.umn.edu" : "University of Minnesota-Crookston",
    "d.umn.edu" : "University of Minnesota-Duluth",
    "mrs.umn.edu" : "University of Minnesota-Morris",
    "umn.edu" : "University of Minnesota-Twin Cities",
    "olemiss.edu" : "University of Mississippi",
    "umsmed.edu" : "University of Mississippi Medical Center",
    "missouri.edu" : "University of Missouri-Columbia",
    "umkc.edu" : "University of Missouri-Kansas City",
    "umr.edu" : "University of Missouri-Rolla",
    "umsl.edu" : "University of Missouri-Saint Louis",
    "umt.edu" : "University of Montana",
    "unk.edu" : "University of Nebraska, Kearney",
    "unl.edu" : "University of Nebraska, Lincoln",
    "unomaha.edu" : "University of Nebraska, Omaha",
    "unlv.edu" : "University of Nevada, Las Vegas",
    "unr.edu" : "University of Nevada, Reno",
    "une.edu" : "University of New England",
    "unh.edu" : "University of New Hampshire, Durham",
    "newhaven.edu" : "University of New Haven",
    "unm.edu" : "University of New Mexico",
    "uno.edu" : "University of New Orleans",
    "unca.edu" : "University of North Carolina at Asheville",
    "unc.edu" : "University of North Carolina at Chapel Hill",
    "uncc.edu" : "University of North Carolina at Charlotte",
    "uncg.edu" : "University of North Carolina at Greensboro",
    "uncwil.edu" : "University of North Carolina at Wilmington",
    "und.nodak.edu" : "University of North Dakota",
    "unf.edu" : "University of North Florida",
    "unt.edu" : "University of North Texas",
    "hsc.unt.edu" : "University of North Texas Health Science Center",
    "univnorthco.edu" : "University of Northern Colorado",
    "uni.edu" : "University of Northern Iowa",
    "nd.edu" : "University of Notre Dame",
    "uoknor.edu" : "University of Oklahoma",
    "uoregon.edu" : "University of Oregon",
    "ozarks.edu" : "University of the Ozarks",
    "uop.edu" : "University of the Pacific",
    "upenn.edu" : "University of Pennsylvania",
    "uophx.edu" : "University of Phoenix",
    "pitt.edu" : "University of Pittsburgh",
    "uofport.edu" : "University of Portland",
    "upr.clu.edu" : "University of Puerto Rico",
    "ups.edu" : "University of Puget Sound",
    "uor.edu" : "University of Redlands",
    "uri.edu" : "University of Rhode Island",
    "urich.edu" : "University of Richmond",
    "rochester.edu" : "University of Rochester",
    "acusd.edu" : "University of San Diego",
    "usfca.edu" : "University of San Francisco",
    "sarasota.fl.us" : "University of Sarasota",
    "usao.edu" : "University of Science & Arts of Oklahoma",
    "uofs.edu" : "University of Scranton",
    "thecoo.edu" : "University of Sioux Falls",
    "usc.edu" : "University of Southern California",
    "scarolina.edu" : "University of South Carolina",
    "sc.edu" : "University of South Carolina - Aiken",
    "usd.edu" : "University of South Dakota",
    "usf.edu" : "University of South Florida",
    "usm.maine.edu" : "University of Southern Maine",
    "usm.edu" : "University of Southern Mississippi",
    "usl.edu" : "University of Southwestern Louisiana",
    "stthom.edu" : "University of Saint Thomas",
    "stthomas.edu" : "University of Saint Thomas, MN",
    "usouthal.edu" : "University of South Alabama",
    "uscolo.edu" : "University of Southern Colorado",
    "usi.edu" : "University of Southern Indiana",
    "utampa.edu" : "University of Tampa",
    "utk.edu" : "University of Tennessee, Knoxville",
    "utm.edu" : "University of Tennessee, Martin",
    "utsystem.edu" : "University of Texas System",
    "uta.edu" : "University of Texas at Arlington",
    "utexas.edu" : "University of Texas at Austin",
    "utb.edu" : "University of Texas at Brownsville",
    "utdallas.edu" : "University of Texas at Dallas",
    "utep.edu" : "University of Texas at El Paso",
    "panam.edu" : "University of Texas-Pan American",
    "utsa.edu" : "University of Texas at San Antonio",
    "uth.tmc.edu" : "University of Texas Health Science Center at Houston",
    "uthscsa.edu" : "University of Texas Health Science Center at San Antonio",
    "uthct.edu" : "University of Texas Health Center at Tyler",
    "utmdacc.uth.tmc.edu" : "University of Texas M.D. Anderson Cancer Center",
    "utmb.edu" : "University of Texas Medical Branch",
    "swmed.edu" : "University of Texas Southwestern Medical Center at Dallas",
    "utoledo.edu" : "University of Toledo",
    "utulsa.edu" : "University of Tulsa",
    "utah.edu" : "University of Utah",
    "uvm.edu" : "University of Vermont",
    "uvi.edu" : "University of the Virgin Islands",
    "virginia.edu" : "University of Virginia, Charlottesville",
    "washington.edu" : "University of Washington",
    "westal.edu" : "University of West Alabama",
    "uwf.edu" : "University of West Florida",
    "uwsa.edu" : "University of Wisconsin System",
    "uwec.edu" : "University of Wisconsin-Eau Claire",
    "uwgb.edu" : "University of Wisconsin-Green Bay",
    "uwlax.edu" : "University of Wisconsin-LaCrosse",
    "wisc.edu" : "University of Wisconsin-Madison",
    "uwm.edu" : "University of Wisconsin-Milwaukee",
    "uwosh.edu" : "University of Wisconsin-Oshkosh",
    "uwp.edu" : "University of Wisconsin-Parkside",
    "uwplatt.edu" : "University of Wisconsin-Platteville",
    "uwrf.edu" : "University of Wisconsin-River Falls",
    "uwsp.edu" : "University of Wisconsin-Stevens Point",
    "uwstout.edu" : "University of Wisconsin-Stout",
    "uwsuper.edu" : "University of Wisconsin-Superior",
    "uww.edu" : "University of Wisconsin-Whitewater",
    "uwyo.edu" : "University of Wyoming",
    "uiu.edu" : "Upper Iowa University",
    "usu.edu" : "Utah State University",
    "uvsc.edu" : "Utah Valley State College",
    "vcsu.nodak.edu" : "Valley City State University",
    "valdosta.peachnet.edu" : "Valdosta State University",
    "valpo.edu" : "Valparaiso University",
    "vanderbilt.edu" : "Vanderbilt University",
    "vassar.edu" : "Vassar College",
    "vtc.vsc.edu" : "Vermont Technical College",
    "vjc.edu" : "Villa Julie College",
    "vill.edu" : "Villanova University",
    "vcu.edu" : "Virginia Commonwealth University",
    "vic.edu" : "Virginia Intermont College",
    "vmi.edu" : "Virginia Military Institute",
    "vt.edu" : "Virginia Polytechnic Institute and State University",
    "vsu.edu" : "Virginia State University",
    "vwc.edu" : "Virginia Wesleyan College",
    "wabash.edu" : "Wabash College",
    "wfu.edu" : "Wake Forest University",
    "waldenu.edu" : "Walden University",
    "wwc.edu" : "Walla Walla College",
    "warren-wilson.edu" : "Warren Wilson College",
    "wartburg.edu" : "Wartburg College",
    "wuacc.edu" : "Washburn University",
    "bible.edu" : "Washington Bible College/Capital Bible Seminary",
    "wlu.edu" : "Washington & Lee University",
    "washcoll.edu" : "Washington College",
    "wsu.edu" : "Washington State University",
    "vancouver.wsu.edu" : "Washington State University at Vancouver",
    "wustl.edu" : "Washington University, Saint Louis",
    "wayne.edu" : "Wayne State University",
    "weber.edu" : "Waynesburg College, waynesburg.edu",
    "websteruniv.edu" : "Webster University",
    "wellesley.edu" : "Wellesley College",
    "wells.edu" : "Wells College",
    "wit.edu" : "Wentworth Institute of Technology",
    "wesley.edu" : "Wesley College",
    "wesleyan.edu" : "Wesleyan University",
    "wcupa.edu" : "West Chester University of Pennsylvania",
    "wcula.edu" : "West Coast University",
    "westga.edu" : "West Georgia College",
    "wlsc.wvnet.edu" : "West Liberty State College",
    "wtamu.edu" : "West Texas A&M University",
    "wvu.edu" : "West Virginia University",
    "wvup.wvnet.edu" : "West Virginia University at Parkersburg",
    "wcu.edu" : "Western Carolina University",
    "wcsu.ctstateu.edu" : "Western Connecticut State University",
    "wiu.edu" : "Western Illinois University",
    "wku.edu" : "Western Kentucky University",
    "wmc.car.md.us" : "Western Maryland College",
    "wmich.edu" : "Western Michigan University",
    "wmc.edu" : "Western Montana College",
    "wnec.edu" : "Western New England College",
    "wnmu.edu" : "Western New Mexico University",
    "wsc.colorado.edu" : "Western State College",
    "wwu.edu" : "Western Washington University",
    "wsc.mass.edu" : "Westfield State College",
    "westminster.edu" : "Westminster College",
    "westminster-mo.edu" : "Westminster College",
    "wcslc.edu" : "Westminster College of Salt Lake City",
    "wts.edu" : "Westminster Theological Seminary",
    "westmont.edu" : "Westmont College",
    "wheaton.edu" : "Wheaton College",
    "wheatonma.edu" : "Wheaton College, Norton MA",
    "wjc.edu" : "Wheeling Jesuit College",
    "whitman.edu" : "Whitman College",
    "whittier.edu" : "Whittier College",
    "whitworth.edu" : "Whitworth College",
    "twsu.edu" : "Wichita State University",
    "widener.edu" : "Widener University",
    "wilberforce.edu" : "Wilberforce University",
    "wilkes.edu" : "Wilkes University",
    "willamette.edu" : "Willamette University",
    "taftu.edu" : "William Howard Taft University",
    "jewell.edu" : "William Jewell College",
    "wmitchell.edu" : "William Mitchell College of Law",
    "wmpenn.edu" : "William Penn College",
    "wilpaterson.edu" : "William Paterson College",
    "wmwoods.edu" : "William Woods University",
    "williams.edu" : "Williams College",
    "wilmington.edu" : "Wilmington College",
    "winona.msus.edu" : "Winona State University",
    "winthrop.edu" : "Winthrop University",
    "wittenberg.edu" : "Wittenberg University",
    "wofford.edu" : "Wofford College",
    "woodburyu.edu" : "Woodbury University",
    "wpi.edu" : "Worcester Polytechnic Institute",
    "wright.edu" : "Wright State University",
    "xula.edu" : "Xavier University of Louisiana",
    "yale.edu" : "Yale University",
    "yu.edu" : "Yeshiva University",
    "ycp.edu" : "York College of Pennsylvania",
    "ysu.edu" : "Youngstown State University"
]
